/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ExamplesFormRouteImport } from './routes/examples/form'
import { Route as ExamplesQueryRouteImport } from './routes/examples/query'
import { Route as ExamplesStoreRouteImport } from './routes/examples/store'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ExamplesFormRoute = ExamplesFormRouteImport.update({
  id: '/examples/form',
  path: '/examples/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesQueryRoute = ExamplesQueryRouteImport.update({
  id: '/examples/query',
  path: '/examples/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesStoreRoute = ExamplesStoreRouteImport.update({
  id: '/examples/store',
  path: '/examples/store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/examples/form': typeof ExamplesFormRoute
  '/examples/query': typeof ExamplesQueryRoute
  '/examples/store': typeof ExamplesStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/examples/form': typeof ExamplesFormRoute
  '/examples/query': typeof ExamplesQueryRoute
  '/examples/store': typeof ExamplesStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/examples/form': typeof ExamplesFormRoute
  '/examples/query': typeof ExamplesQueryRoute
  '/examples/store': typeof ExamplesStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/examples/form'
    | '/examples/query'
    | '/examples/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/examples/form'
    | '/examples/query'
    | '/examples/store'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/_authenticated/dashboard'
    | '/examples/form'
    | '/examples/query'
    | '/examples/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ExamplesFormRoute: typeof ExamplesFormRoute
  ExamplesQueryRoute: typeof ExamplesQueryRoute
  ExamplesStoreRoute: typeof ExamplesStoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/examples/form': {
      id: '/examples/form'
      path: '/examples/form'
      fullPath: '/examples/form'
      preLoaderRoute: typeof ExamplesFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/query': {
      id: '/examples/query'
      path: '/examples/query'
      fullPath: '/examples/query'
      preLoaderRoute: typeof ExamplesQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/store': {
      id: '/examples/store'
      path: '/examples/store'
      fullPath: '/examples/store'
      preLoaderRoute: typeof ExamplesStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ExamplesFormRoute: ExamplesFormRoute,
  ExamplesQueryRoute: ExamplesQueryRoute,
  ExamplesStoreRoute: ExamplesStoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
